### PR TITLE
Address String.to_char_list deprecations

### PR DESCRIPTION
**Pull request by zfletch**
When running the code with Elixir version 1.5.1, the following warnings are generated:

```
warning: String.to_char_list/1 is deprecated, use String.to_charlist/1
  lib/secure_compare.ex:7

warning: String.to_char_list/1 is deprecated, use String.to_charlist/1
  lib/secure_compare.ex:8
```

This PR updates the code to use `to_charlist` in order to address the warning.

There's some discussion about the two functions [here](https://github.com/elixir-lang/elixir/issues/4909)

### CODE REVIEW

**Comment by zfletch** [comment]
It looks like this breaks for Elixir 1.2.6 since it was introduced in 1.3. I'm not sure which Elixir versions you'd like to support? I think `to_char_list` will be removed from Elixir in 2.0 (https://hexdocs.pm/elixir/deprecations.html)

**Comment by plackemacher** [comment]
Sorry for the delay on this. I've added some commits to your branch. I'm okay with dropping support for versions of Elixir less than 1.3 and therefore bumping the version up to `0.1.0`. If Travis passes on this, I'll merge it and hopefully do a release today. Thanks for the PR! 👍

**Comment by plackemacher** [comment]
@zfletch version 0.1.0 has been published to hex. Thanks again!

**Comment by zfletch** [comment]
Thanks!

**Pull request merged**
